# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Text',
            field=models.TextField(max_length=1000),
        ),
    ]
