# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipee',
            new_name='Recipe',
        ),
    ]
