# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_auto_20170907_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Preparation_Time',
            field=models.IntegerField(),
        ),
    ]
